-- MySQL Script generated by MySQL Workbench
-- Sat Jul 19 00:17:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Event` (
  `EventID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `StartTime` TIME NOT NULL,
  `EndTime` TIME NULL,
  PRIMARY KEY (`EventID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Participant` (
  `ParticipantID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ParticipantID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ParticipatesIn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ParticipatesIn` (
  `EventID` INT NOT NULL,
  `ParticipantID` INT NOT NULL,
  PRIMARY KEY (`EventID`, `ParticipantID`),
  INDEX `fk_Event_has_Participant_Participant1_idx` (`ParticipantID` ASC) VISIBLE,
  INDEX `fk_Event_has_Participant_Event_idx` (`EventID` ASC) VISIBLE,
  CONSTRAINT `fk_Event_has_Participant_Event`
    FOREIGN KEY (`EventID`)
    REFERENCES `mydb`.`Event` (`EventID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Event_has_Participant_Participant1`
    FOREIGN KEY (`ParticipantID`)
    REFERENCES `mydb`.`Participant` (`ParticipantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
